spring.application.name=i-bot
spring.datasource.url=jdbc:postgresql://localhost:5432/i-bot
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB